### ISSUE TITLE
0.23.4 recipe change

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/pytest-asyncio-feedstock#41]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The 0.23.4 build is failing because the pytest dependency has been modified in the pip package to be `<8.0`. That same change needs to be made to the conda recipe.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by bollwyvl** [comment]
With #40 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/653 there isn't much else left to do.
